### ISSUE TITLE
CREATE_CL_COMMAND fails with long comments longer than 30 chars

### ISSUE THREAD

**Issue by chrjorgensen** [NielsLiisberg/command-for-SQL#1]
When creating a command for a function with a long comment longer than 30 characters, the compile of the command fails since the long comment is used for the PROMPT parameter - and this only supports up to 30 characters in length.

```
                                     Command Definition Source                                                 
 SEQNBR  *...+... 1 ...+... 2 ...+... 3 ...+... 4 ...+... 5 ...+... 6 ...+... 7 ...+... 8 ...+... 9 ...+.  DATE
       -  CMD PROMPT('Convert system timestamp to regular timestamp')                                          
* CPD0074  30  Value 'Convert sy' for PROMPT exceeds 30 characters.                                            
```

**Comment by NielsLiisberg** [comment]
Thanx - Is on the list !!

**Comment by NielsLiisberg** [comment]
You Can alternatively use the “label on procedure” go give it a good name
for the command. It will honor this when creating the command object

tir. 8. feb. 2022 kl. 16.37 skrev Christian Jorgensen <
***@***.***>:
